# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ToDoApp/ToDoApp.sln
    - name: Build
      run: dotnet build ToDoApp/ToDoApp.sln --no-restore
    - name: Test
      run: dotnet test ToDoApp/ToDoApp.sln --no-build --verbosity normal
